services:
  - type: web
    name: users-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
